### ISSUE TITLE
API Implementation - Fetch readme from GitHub

### ISSUE THREAD

**Issue by fikretellek** [RbAvci/Read-me-Hire-me#15]
## Story

- **As a** function

- **I Want** to fetch Github API for readme data

- **So That** store that data in database

## Acceptance Criteria

1. Given a GitHub correct username as a parameter
   - When the function gets executed
   - Then the function should get the readme data from GitHub, store it in database and return true
2. Given a GitHub username as a parameter
   - When the function can not get the data
   - Then the function should return error with relevant message
3. Given a GitHub username as a parameter
   - When the function can not store data to database
   - Then the function should return error with relevant message

## Implementation Notes

1. this should be a function that will be used for signup fetch endpoint.
2. it should be exported and created under functions folder
3. please include comments tho explain steps
4.for the future reference, are empty readme's still should be allowed to sign up?

## Checklist:

- [x] I have defined the user story
- [x] I have defined some acceptance criteria
- [x] I have included any implementation notes
- [x] I have included all relevant links (no relevant links)

**Comment by ozgulsal** [comment]
#26

**Comment by fikretellek** [comment]
#47
