### ISSUE TITLE
Reset password  if the user forgot password

### ISSUE THREAD

**Issue by RbAvci** [RbAvci/Read-me-Hire-me#45]
**Description:**
Implement a feature allowing users to reset their password if they have forgotten it.

**Comment by ozgulsal** [comment]
#43

**Comment by RbAvci** [comment]
We need to talk about this, I created the UI part but for the backend, we need to get Users email in the beginning. This changes the data scheme... So I didn't open PR for this. We need to send to user email to reset the password. It is not possible now.
